name: mariposa_test
version: 1.0.0
author: Tobechukwu Osakwe <thosakwe@gmail.com>
homepage: https://github.com/mariposa-dart/test
description: Infrastructure for unit-testing Mariposa widgets.
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  html_builder: ^1.0.0
  matcher: ^0.12.0
  mariposa: ^1.0.0
dev_dependencies:
  test: ^0.12.0
  zen: ^1.0.0